flask-taskr - blueprint/app/models.py
#models.py

from app.views import db

class FTasks(db.Model):
	__tablename__= "ftasks"
	
	task_id=db.Column(db.Integer, primary_key=True)
	name=db.Column(db.String,nullable=False)
	due_date=db.Column(db.Date,nullable=False)
	priority=db.Column(db.Integer,nullable=False)
	posted_date = db.Column(db.Date, nullable=False)
	status=db.Column(db.Integer)
	user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
	
	def __init__(self, name, due_date, priority,posted_date, status,user_id):
		self.name=name
		self.due_date=due_date
		self.priority=priority
		self.posted_date = posted_date
		self.status=status
		self.user_id = user_id
	
	def __repr__(self):
		return '<name %r>' % (self.body)

		
class User(db.Model):
	__tablename__ = 'users'
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String, unique=True, nullable=False)
	email = db.Column(db.String, unique=True, nullable=False)
	password = db.Column(db.String, nullable=False)
	tasks = db.relationship('FTasks', backref='poster')
	
	def __init__(self, name=None, email=None, password=None):
		self.name = name
		self.email = email
		self.password = password
	
	def __repr__(self):
		return '<User %r>' % (self.name)

flask-taskr - blueprint/app/tasks/forms.py
# /apps/tasks/forms.py
from flask_wtf import Form
from wtforms import TextField, DateField, IntegerField, SelectField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length


class AddTask(Form):
	task_id = IntegerField('Priority')
	name = TextField('Task Name', validators=[DataRequired()])
	due_date = DateField('Date Due (mm/dd/yyyy)', validators=[DataRequired()],format='%m/%d/%Y')
	priority = SelectField('Priority', validators=[DataRequired()], choices=[('1', '1'),('2', '2'),('3', '3'), ('4', '4'),('5', '5')])
	status = IntegerField('Status')
	posted_date = DateField('Posted Date (mm/dd/yyyy)', validators=[DataRequired()],format='%m/%d/%Y')

flask-taskr - blueprint/app/users/forms.py
# /app/users/forms.py

from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length

class RegisterForm(Form):
	name = TextField('Username', validators=[DataRequired(), Length(min=2,max=25)])
	email = TextField('Email', validators=[DataRequired(), Length(min=2,max=40)])
	password = PasswordField('Password', validators=[DataRequired(),Length(min=2, max=40)])
	confirm = PasswordField('Repeat Password',[DataRequired(),EqualTo('password', message='Passwords must match')])

class LoginForm(Form):
	name = TextField('Username', validators=[DataRequired()])
	password = PasswordField('Password', validators=[DataRequired()])
	

flask-taskr - blueprint/app/__init__.py
#/app/__init__.py

from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy

app=Flask(__name__)
app.config.from_object('config')
db=SQLAlchemy(app)


if not app.debug:
	import os
	import logging

	from logging import Formatter, FileHandler
	from config import basedir

	file_handler = FileHandler(os.path.join(basedir,'error.log'))
	file_handler.setFormatter(Formatter('%(asctime)s %(levelname)s:	%(message)s ''[in %(pathname)s:%(lineno)d]'))
	app.logger.setLevel(logging.DEBUG)
	file_handler.setLevel(logging.DEBUG)
	app.logger.addHandler(file_handler)
	app.logger.info('errors')
	app.logger.error('errors')
	app.logger.debug('errors')

from app import views, models
from app.users.views import mod as usersMod
from app.tasks.views import mod as tasksMod

app.register_blueprint(usersMod)
app.register_blueprint(tasksMod)

flask-taskr - blueprint/app/tasks/views.py
#flask-taskr-SQLAlchemy
#views.py
#/app/tasks/views.py

from app import db
from flask import Blueprint, Flask,render_template, request, session,flash,redirect,url_for,g
from app.views import login_required, flash_errors
from app.models import FTasks
from app.tasks.forms import AddTask


mod = Blueprint('tasks', __name__, url_prefix='/tasks', template_folder='templates', static_folder='static')


	
@mod.route('/tasks',methods=['GET','POST'])
#@login_required
def tasks():
#use SQLAlchemy wrapper
	
	
	open_tasks=db.session.query(FTasks).filter_by(status='1').order_by(FTasks.due_date.asc())
	closed_tasks=db.session.query(FTasks).filter_by(status='0').order_by(FTasks.due_date.asc())
	
	return render_template('tasks/tasks.html',form=AddTask(request.form),open_tasks=open_tasks, closed_tasks=closed_tasks)
	
#Add new tasks
@mod.route('/add',methods=['GET','POST'])
#@login_required
def new_task():
	form=AddTask(request.form,csrf_enabled=False)
	if form.validate_on_submit():
		new_task=FTasks(
					form.name.data,
					form.due_date.data,
					form.priority.data,
					form.posted_date.data,
					'1',
					session['user_id']
					)
		db.session.add(new_task)
		db.session.commit()
		flash('New entry was successfully posted')
	else:
		flash_errors(form)
	
	return redirect(url_for('.tasks'))

#Mark tasks as complete
@mod.route('/complete/<int:task_id>')
@login_required
def complete(task_id):
	new_id=task_id
	db.session.query(FTasks).filter_by(task_id=new_id).update({"status":"0"})
	db.session.commit()
	flash('The task was marked as complete')
	return redirect(url_for('.tasks'))

#Delete tasks
@mod.route('/delete/<int:task_id>/')
@login_required
def delete_entry(task_id):
	
	new_id=task_id
	db.session.query(FTasks).filter_by(task_id=new_id).delete()
	db.session.commit()
	flash('The task was deleted')
	return redirect(url_for('.tasks'))

flask-taskr - blueprint/app/users/views.py
#flask-taskr-SQLAlchemy
#views.py
#/app/users/views.py

from app import db
from flask import Blueprint, Flask,render_template, request, session,flash,redirect,url_for,g
from app.views import login_required, flash_errors
from app.users.forms import RegisterForm, LoginForm
from app.models import User
from sqlalchemy.exc import IntegrityError

mod = Blueprint('users', __name__, url_prefix='/users', template_folder='templates', static_folder='static')


@mod.route('/logout')
def logout():
	session.pop('logged_in',None)
	session.pop('user_id', None)
	flash('You are now logged out. See you again:)')
	return redirect(url_for('login'))

	
@mod.route('/',methods=['GET','POST'])
def login():
	error=None
	# from pprint import pprint
	# pprint(request.form)
    # # If you need headers just comment out next line. 
	# pprint(request.headers)
	if request.method=='POST':
		u = User.query.filter_by(name=request.form['name'],password=request.form['password']).first()
		if u is None:
			error = 'Invalid username or password.'
			print("Invalid username or password")
		else:
			session['logged_in']=True
			print("Logged in!")
			session['user_id'] = u.id
			flash('You are logged in. Go Crazy.')
			return redirect(url_for('tasks.tasks'))
	#else:
		#

	#from pprint import pprint
	pprint(request.form)
    # If you need headers just comment out next line. 
	pprint(request.headers)
	return render_template('users/login.html',form = LoginForm(request.form),error=error)


	
@mod.route('/register/', methods=['GET','POST'])
def register():
	error = None
	form = RegisterForm(request.form, csrf_enabled=False)
	if form.validate_on_submit():
		new_user = User(form.name.data,form.email.data,form.password.data,)
		try:
			db.session.add(new_user)
			db.session.commit()
			flash('Thanks for registering. Please login.')
			return redirect(url_for('.login'))
		except IntegrityError:
			error = 'Oh no! That username and/or email already exist.Please try again.'
	else:
		flash_errors(form)
	return render_template('/users/register.html', form=form, error=error)

flask-taskr - blueprint/app/views.py
#/app/views.py

from app import app, db
from flask import Blueprint, Flask,render_template, request, session,flash,redirect,url_for,g
from functools import wraps
from app.models import FTasks

#app=Flask(__name__)
#app.config.from_object('config')
#db=SQLAlchemy(app)

def flash_errors(form):
	for field, errors in form.errors.items():
		for error in errors:
			flash(u"Error in the %s field - %s" % (getattr(form, field).label.text,error), 'error')


def login_required(test):
	@wraps(test)
	def wrap(*args,**kwargs):
		if 'logged_in' in session:
			return test(*args,**kwargs)
		else:
			flash('You need to login first')
			return redirect(url_for('users.login'))
	return wrap

@app.errorhandler(500)
def internal_error(error):
	db.session.rollback()
	return render_template('500.html'), 500

@app.errorhandler(404)
def internal_error(error):
	return render_template('404.html'), 404

@app.route('/', defaults={'page': 'index'})
def index(page):
	return(redirect(url_for('users.login')))

flask-taskr - blueprint/app/templates/template.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <title>Welcome to the FlaskTaskr, Friends!</title>
</head>

<body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">FlaskTaskr</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    {% if not session.logged_in %}
                    <li><a href={{url_for('users.register')}}>Signup</a>
                    </li>
                    {% else %}
                    <li><a href={{url_for('users.logout')}}>Logout</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>


<div class="container">
 <div class="content">
 {% for message in get_flashed_messages() %}
 <div class=flash>{{ message }}</div>
 <br>
        {% endfor %} {% if error %}
        <div class="error"><strong>Error:</strong>{{ error }}</div>
        {% endif %}
        <!--inheritance-->
        {% block content %} {% endblock %}
        <!-- end inheritance -->
    </div>
	<div class="footer">
 <hr>
 <p>&copy;<a href="http://www.realpython.com">Voila</a></p>
 </div>
 </div><!-- /.container -->
 <!-- scripts -->
 <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
 <script
src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
</body>

</html>